"""Build config/companies.yaml from the SimplifyJobs lists.

The lists already encode company -> ATS URL, so the 150-300 target companies do
not have to be typed by hand. Hand-editing after the fact is expected: this file
is the job-search strategy made explicit, and the generated version is only a
starting point.
"""
from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

from .config import CONFIG_DIR
from .http import get_json
from .sources import simplify

SUPPORTED = {"greenhouse", "lever", "ashby"}
_SAFE_SLUG = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,80}$")


def discover(min_postings: int = 1) -> tuple[list[dict], Counter]:
    """Return (company entries, vendor histogram) across both lists."""
    found: dict[tuple[str, str], dict] = {}
    vendors: Counter = Counter()

    for list_key, url in simplify.LISTS.items():
        payload, _ = get_json(url, timeout=60)
        if not isinstance(payload, list):
            continue
        for row in payload:
            if not row.get("active") or not row.get("is_visible"):
                continue
            ats = simplify.detect_ats(row.get("url") or "")
            if not ats:
                continue
            vendor, slug = ats
            vendors[vendor] += 1
            if vendor not in SUPPORTED or not _SAFE_SLUG.match(slug):
                continue
            key = (vendor, slug.lower())
            entry = found.setdefault(key, {
                "name": row.get("company_name") or slug,
                "ats": vendor,
                "slug": slug,
                "seen": 0,
                "lists": set(),
            })
            entry["seen"] += 1
            entry["lists"].add(list_key)

    entries = [e for e in found.values() if e["seen"] >= min_postings]
    entries.sort(key=lambda e: (-e["seen"], e["name"].lower()))
    return entries, vendors


def render(entries: list[dict]) -> str:
    lines = [
        "# Target companies. Generated by `jobs bootstrap`, then hand-edited.",
        "#",
        "# `seen` is how many live postings the SimplifyJobs lists had for this",
        "# company when the file was generated — a rough proxy for how much they",
        "# hire, not a ranking. Delete companies you would not work at; the point",
        "# of this file is that it is opinionated.",
        "#",
        "# Workday and SmartRecruiters companies are intentionally absent: no",
        "# ingester for them yet (Workday is Lane B in the plan and barely worth",
        "# automating).",
        "",
        "# Aggregate lists, polled whole.",
        "lists:",
    ]
    for key in simplify.LISTS:
        lines.append(f"  - {key}")
    lines += ["", "companies:"]
    for e in entries:
        lists = ",".join(sorted(e["lists"]))
        name = e["name"].replace('"', "'")
        lines.append(f'  - name: "{name}"')
        lines.append(f"    ats: {e['ats']}")
        lines.append(f"    slug: {e['slug']}")
        lines.append(f"    seen: {e['seen']}   # from: {lists}")
    return "\n".join(lines) + "\n"


def write(path: Path | None = None, min_postings: int = 1) -> dict:
    path = path or (CONFIG_DIR / "companies.yaml")
    entries, vendors = discover(min_postings=min_postings)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(entries), encoding="utf-8")
    return {"companies": len(entries), "vendors": dict(vendors), "path": str(path)}
